#ifndef _LICENSE_H
#define _LICENSE_H

static const char *header_string =
    "{\\rtf1\\ansi\n"
    "{\\b FTSW-1 Updater}\\line\n"
    "https://github.com/MegabytePhreak/scope-footswitch \\line\n"
    "\\line Copyright 2019 Paul Roukema\\line\n"
    "GNU General Public License (GPL) v3 or later\\line\n"
    "\\line\n{\\b Usage:}\\line\n"
    "1. Turn off FTSW-1 and connect to this PC with micro-USB cable.\\line\n"
    "2. Press and hold front button on FTSW-1 while turning on power switch "
    "(Mode switch should flash).\\line\n"
    "3. Refresh device list in main window.\\line\n"
    "4. Click program to update firmware. \\line\n"
    "}";
static const char *license_string =
    "{\\rtf1\\ansi\n"
    "Some code and many concepts from Rufus\\line\n"
    "https://rufus.ie/ \\line\n"
    "GNU General Public License (GPL) v3 or later\\line\n"
    "\\line\n\\line\n"
    "                    GNU GENERAL PUBLIC LICENSE\\line\n"
    "                       Version 3, 29 June 2007\\line\n"
    "\\line\n"
    " Copyright (C) 2007 Free Software Foundation, Inc. "
    "<http://fsf.org/>\\line\n"
    " Everyone is permitted to copy and distribute verbatim copies\\line\n"
    " of this license document, but changing it is not allowed.\\line\n"
    "\\line\n"
    "                            Preamble\\line\n"
    "\\line\n"
    "  The GNU General Public License is a free, copyleft license for\\line\n"
    "software and other kinds of works.\\line\n"
    "\\line\n"
    "  The licenses for most software and other practical works are "
    "designed\\line\n"
    "to take away your freedom to share and change the works.  By "
    "contrast,\\line\n"
    "the GNU General Public License is intended to guarantee your freedom "
    "to\\line\n"
    "share and change all versions of a program--to make sure it remains "
    "free\\line\n"
    "software for all its users.  We, the Free Software Foundation, use "
    "the\\line\n"
    "GNU General Public License for most of our software; it applies also "
    "to\\line\n"
    "any other work released this way by its authors.  You can apply it "
    "to\\line\n"
    "your programs, too.\\line\n"
    "\\line\n"
    "  When we speak of free software, we are referring to freedom, not\\line\n"
    "price.  Our General Public Licenses are designed to make sure that "
    "you\\line\n"
    "have the freedom to distribute copies of free software (and charge "
    "for\\line\n"
    "them if you wish), that you receive source code or can get it if "
    "you\\line\n"
    "want it, that you can change the software or use pieces of it in "
    "new\\line\n"
    "free programs, and that you know you can do these things.\\line\n"
    "\\line\n"
    "  To protect your rights, we need to prevent others from denying "
    "you\\line\n"
    "these rights or asking you to surrender the rights.  Therefore, you "
    "have\\line\n"
    "certain responsibilities if you distribute copies of the software, or "
    "if\\line\n"
    "you modify it: responsibilities to respect the freedom of others.\\line\n"
    "\\line\n"
    "  For example, if you distribute copies of such a program, whether\\line\n"
    "gratis or for a fee, you must pass on to the recipients the same\\line\n"
    "freedoms that you received.  You must make sure that they, too, "
    "receive\\line\n"
    "or can get the source code.  And you must show them these terms so "
    "they\\line\n"
    "know their rights.\\line\n"
    "\\line\n"
    "  Developers that use the GNU GPL protect your rights with two "
    "steps:\\line\n"
    "(1) assert copyright on the software, and (2) offer you this "
    "License\\line\n"
    "giving you legal permission to copy, distribute and/or modify it.\\line\n"
    "\\line\n"
    "  For the developers' and authors' protection, the GPL clearly "
    "explains\\line\n"
    "that there is no warranty for this free software.  For both users' "
    "and\\line\n"
    "authors' sake, the GPL requires that modified versions be marked "
    "as\\line\n"
    "changed, so that their problems will not be attributed erroneously "
    "to\\line\n"
    "authors of previous versions.\\line\n"
    "\\line\n"
    "  Some devices are designed to deny users access to install or run\\line\n"
    "modified versions of the software inside them, although the "
    "manufacturer\\line\n"
    "can do so.  This is fundamentally incompatible with the aim of\\line\n"
    "protecting users' freedom to change the software.  The systematic\\line\n"
    "pattern of such abuse occurs in the area of products for individuals "
    "to\\line\n"
    "use, which is precisely where it is most unacceptable.  Therefore, "
    "we\\line\n"
    "have designed this version of the GPL to prohibit the practice for "
    "those\\line\n"
    "products.  If such problems arise substantially in other domains, "
    "we\\line\n"
    "stand ready to extend this provision to those domains in future "
    "versions\\line\n"
    "of the GPL, as needed to protect the freedom of users.\\line\n"
    "\\line\n"
    "  Finally, every program is threatened constantly by software "
    "patents.\\line\n"
    "States should not allow patents to restrict development and use of\\line\n"
    "software on general-purpose computers, but in those that do, we wish "
    "to\\line\n"
    "avoid the special danger that patents applied to a free program "
    "could\\line\n"
    "make it effectively proprietary.  To prevent this, the GPL assures "
    "that\\line\n"
    "patents cannot be used to render the program non-free.\\line\n"
    "\\line\n"
    "  The precise terms and conditions for copying, distribution and\\line\n"
    "modification follow.\\line\n"
    "\\line\n"
    "                       TERMS AND CONDITIONS\\line\n"
    "\\line\n"
    "  0. Definitions.\\line\n"
    "\\line\n"
    "  \"This License\" refers to version 3 of the GNU General Public "
    "License.\\line\n"
    "\\line\n"
    "  \"Copyright\" also means copyright-like laws that apply to other kinds "
    "of\\line\n"
    "works, such as semiconductor masks.\\line\n"
    "\\line\n"
    "  \"The Program\" refers to any copyrightable work licensed under "
    "this\\line\n"
    "License.  Each licensee is addressed as \"you\".  \"Licensees\" "
    "and\\line\n"
    "\"recipients\" may be individuals or organizations.\\line\n"
    "\\line\n"
    "  To \"modify\" a work means to copy from or adapt all or part of the "
    "work\\line\n"
    "in a fashion requiring copyright permission, other than the making of "
    "an\\line\n"
    "exact copy.  The resulting work is called a \"modified version\" of "
    "the\\line\n"
    "earlier work or a work \"based on\" the earlier work.\\line\n"
    "\\line\n"
    "  A \"covered work\" means either the unmodified Program or a work "
    "based\\line\n"
    "on the Program.\\line\n"
    "\\line\n"
    "  To \"propagate\" a work means to do anything with it that, "
    "without\\line\n"
    "permission, would make you directly or secondarily liable for\\line\n"
    "infringement under applicable copyright law, except executing it on "
    "a\\line\n"
    "computer or modifying a private copy.  Propagation includes "
    "copying,\\line\n"
    "distribution (with or without modification), making available to "
    "the\\line\n"
    "public, and in some countries other activities as well.\\line\n"
    "\\line\n"
    "  To \"convey\" a work means any kind of propagation that enables "
    "other\\line\n"
    "parties to make or receive copies.  Mere interaction with a user "
    "through\\line\n"
    "a computer network, with no transfer of a copy, is not conveying.\\line\n"
    "\\line\n"
    "  An interactive user interface displays \"Appropriate Legal "
    "Notices\"\\line\n"
    "to the extent that it includes a convenient and prominently "
    "visible\\line\n"
    "feature that (1) displays an appropriate copyright notice, and (2)\\line\n"
    "tells the user that there is no warranty for the work (except to "
    "the\\line\n"
    "extent that warranties are provided), that licensees may convey "
    "the\\line\n"
    "work under this License, and how to view a copy of this License.  "
    "If\\line\n"
    "the interface presents a list of user commands or options, such as "
    "a\\line\n"
    "menu, a prominent item in the list meets this criterion.\\line\n"
    "\\line\n"
    "  1. Source Code.\\line\n"
    "\\line\n"
    "  The \"source code\" for a work means the preferred form of the "
    "work\\line\n"
    "for making modifications to it.  \"Object code\" means any "
    "non-source\\line\n"
    "form of a work.\\line\n"
    "\\line\n"
    "  A \"Standard Interface\" means an interface that either is an "
    "official\\line\n"
    "standard defined by a recognized standards body, or, in the case "
    "of\\line\n"
    "interfaces specified for a particular programming language, one "
    "that\\line\n"
    "is widely used among developers working in that language.\\line\n"
    "\\line\n"
    "  The \"System Libraries\" of an executable work include anything, "
    "other\\line\n"
    "than the work as a whole, that (a) is included in the normal form "
    "of\\line\n"
    "packaging a Major Component, but which is not part of that Major\\line\n"
    "Component, and (b) serves only to enable use of the work with that\\line\n"
    "Major Component, or to implement a Standard Interface for which an\\line\n"
    "implementation is available to the public in source code form.  A\\line\n"
    "\"Major Component\", in this context, means a major essential "
    "component\\line\n"
    "(kernel, window system, and so on) of the specific operating "
    "system\\line\n"
    "(if any) on which the executable work runs, or a compiler used to\\line\n"
    "produce the work, or an object code interpreter used to run it.\\line\n"
    "\\line\n"
    "  The \"Corresponding Source\" for a work in object code form means "
    "all\\line\n"
    "the source code needed to generate, install, and (for an "
    "executable\\line\n"
    "work) run the object code and to modify the work, including scripts "
    "to\\line\n"
    "control those activities.  However, it does not include the work's\\line\n"
    "System Libraries, or general-purpose tools or generally available "
    "free\\line\n"
    "programs which are used unmodified in performing those activities "
    "but\\line\n"
    "which are not part of the work.  For example, Corresponding Source\\line\n"
    "includes interface definition files associated with source files "
    "for\\line\n"
    "the work, and the source code for shared libraries and dynamically\\line\n"
    "linked subprograms that the work is specifically designed to "
    "require,\\line\n"
    "such as by intimate data communication or control flow between "
    "those\\line\n"
    "subprograms and other parts of the work.\\line\n"
    "\\line\n"
    "  The Corresponding Source need not include anything that users\\line\n"
    "can regenerate automatically from other parts of the Corresponding\\line\n"
    "Source.\\line\n"
    "\\line\n"
    "  The Corresponding Source for a work in source code form is that\\line\n"
    "same work.\\line\n"
    "\\line\n"
    "  2. Basic Permissions.\\line\n"
    "\\line\n"
    "  All rights granted under this License are granted for the term "
    "of\\line\n"
    "copyright on the Program, and are irrevocable provided the stated\\line\n"
    "conditions are met.  This License explicitly affirms your "
    "unlimited\\line\n"
    "permission to run the unmodified Program.  The output from running "
    "a\\line\n"
    "covered work is covered by this License only if the output, given "
    "its\\line\n"
    "content, constitutes a covered work.  This License acknowledges "
    "your\\line\n"
    "rights of fair use or other equivalent, as provided by copyright "
    "law.\\line\n"
    "\\line\n"
    "  You may make, run and propagate covered works that you do not\\line\n"
    "convey, without conditions so long as your license otherwise "
    "remains\\line\n"
    "in force.  You may convey covered works to others for the sole "
    "purpose\\line\n"
    "of having them make modifications exclusively for you, or provide "
    "you\\line\n"
    "with facilities for running those works, provided that you comply "
    "with\\line\n"
    "the terms of this License in conveying all material for which you "
    "do\\line\n"
    "not control copyright.  Those thus making or running the covered "
    "works\\line\n"
    "for you must do so exclusively on your behalf, under your "
    "direction\\line\n"
    "and control, on terms that prohibit them from making any copies of\\line\n"
    "your copyrighted material outside their relationship with you.\\line\n"
    "\\line\n"
    "  Conveying under any other circumstances is permitted solely "
    "under\\line\n"
    "the conditions stated below.  Sublicensing is not allowed; section "
    "10\\line\n"
    "makes it unnecessary.\\line\n"
    "\\line\n"
    "  3. Protecting Users' Legal Rights From Anti-Circumvention Law.\\line\n"
    "\\line\n"
    "  No covered work shall be deemed part of an effective "
    "technological\\line\n"
    "measure under any applicable law fulfilling obligations under "
    "article\\line\n"
    "11 of the WIPO copyright treaty adopted on 20 December 1996, or\\line\n"
    "similar laws prohibiting or restricting circumvention of such\\line\n"
    "measures.\\line\n"
    "\\line\n"
    "  When you convey a covered work, you waive any legal power to "
    "forbid\\line\n"
    "circumvention of technological measures to the extent such "
    "circumvention\\line\n"
    "is effected by exercising rights under this License with respect "
    "to\\line\n"
    "the covered work, and you disclaim any intention to limit operation "
    "or\\line\n"
    "modification of the work as a means of enforcing, against the "
    "work's\\line\n"
    "users, your or third parties' legal rights to forbid circumvention "
    "of\\line\n"
    "technological measures.\\line\n"
    "\\line\n"
    "  4. Conveying Verbatim Copies.\\line\n"
    "\\line\n"
    "  You may convey verbatim copies of the Program's source code as "
    "you\\line\n"
    "receive it, in any medium, provided that you conspicuously and\\line\n"
    "appropriately publish on each copy an appropriate copyright "
    "notice;\\line\n"
    "keep intact all notices stating that this License and any\\line\n"
    "non-permissive terms added in accord with section 7 apply to the "
    "code;\\line\n"
    "keep intact all notices of the absence of any warranty; and give "
    "all\\line\n"
    "recipients a copy of this License along with the Program.\\line\n"
    "\\line\n"
    "  You may charge any price or no price for each copy that you "
    "convey,\\line\n"
    "and you may offer support or warranty protection for a fee.\\line\n"
    "\\line\n"
    "  5. Conveying Modified Source Versions.\\line\n"
    "\\line\n"
    "  You may convey a work based on the Program, or the modifications "
    "to\\line\n"
    "produce it from the Program, in the form of source code under the\\line\n"
    "terms of section 4, provided that you also meet all of these "
    "conditions:\\line\n"
    "\\line\n"
    "    a) The work must carry prominent notices stating that you "
    "modified\\line\n"
    "    it, and giving a relevant date.\\line\n"
    "\\line\n"
    "    b) The work must carry prominent notices stating that it is\\line\n"
    "    released under this License and any conditions added under "
    "section\\line\n"
    "    7.  This requirement modifies the requirement in section 4 to\\line\n"
    "    \"keep intact all notices\".\\line\n"
    "\\line\n"
    "    c) You must license the entire work, as a whole, under this\\line\n"
    "    License to anyone who comes into possession of a copy.  This\\line\n"
    "    License will therefore apply, along with any applicable section "
    "7\\line\n"
    "    additional terms, to the whole of the work, and all its parts,\\line\n"
    "    regardless of how they are packaged.  This License gives no\\line\n"
    "    permission to license the work in any other way, but it does "
    "not\\line\n"
    "    invalidate such permission if you have separately received it.\\line\n"
    "\\line\n"
    "    d) If the work has interactive user interfaces, each must "
    "display\\line\n"
    "    Appropriate Legal Notices; however, if the Program has "
    "interactive\\line\n"
    "    interfaces that do not display Appropriate Legal Notices, your\\line\n"
    "    work need not make them do so.\\line\n"
    "\\line\n"
    "  A compilation of a covered work with other separate and "
    "independent\\line\n"
    "works, which are not by their nature extensions of the covered "
    "work,\\line\n"
    "and which are not combined with it such as to form a larger "
    "program,\\line\n"
    "in or on a volume of a storage or distribution medium, is called "
    "an\\line\n"
    "\"aggregate\" if the compilation and its resulting copyright are "
    "not\\line\n"
    "used to limit the access or legal rights of the compilation's "
    "users\\line\n"
    "beyond what the individual works permit.  Inclusion of a covered "
    "work\\line\n"
    "in an aggregate does not cause this License to apply to the other\\line\n"
    "parts of the aggregate.\\line\n"
    "\\line\n"
    "  6. Conveying Non-Source Forms.\\line\n"
    "\\line\n"
    "  You may convey a covered work in object code form under the "
    "terms\\line\n"
    "of sections 4 and 5, provided that you also convey the\\line\n"
    "machine-readable Corresponding Source under the terms of this "
    "License,\\line\n"
    "in one of these ways:\\line\n"
    "\\line\n"
    "    a) Convey the object code in, or embodied in, a physical "
    "product\\line\n"
    "    (including a physical distribution medium), accompanied by the\\line\n"
    "    Corresponding Source fixed on a durable physical medium\\line\n"
    "    customarily used for software interchange.\\line\n"
    "\\line\n"
    "    b) Convey the object code in, or embodied in, a physical "
    "product\\line\n"
    "    (including a physical distribution medium), accompanied by a\\line\n"
    "    written offer, valid for at least three years and valid for as\\line\n"
    "    long as you offer spare parts or customer support for that "
    "product\\line\n"
    "    model, to give anyone who possesses the object code either (1) "
    "a\\line\n"
    "    copy of the Corresponding Source for all the software in the\\line\n"
    "    product that is covered by this License, on a durable physical\\line\n"
    "    medium customarily used for software interchange, for a price "
    "no\\line\n"
    "    more than your reasonable cost of physically performing this\\line\n"
    "    conveying of source, or (2) access to copy the\\line\n"
    "    Corresponding Source from a network server at no charge.\\line\n"
    "\\line\n"
    "    c) Convey individual copies of the object code with a copy of "
    "the\\line\n"
    "    written offer to provide the Corresponding Source.  This\\line\n"
    "    alternative is allowed only occasionally and noncommercially, "
    "and\\line\n"
    "    only if you received the object code with such an offer, in "
    "accord\\line\n"
    "    with subsection 6b.\\line\n"
    "\\line\n"
    "    d) Convey the object code by offering access from a designated\\line\n"
    "    place (gratis or for a charge), and offer equivalent access to "
    "the\\line\n"
    "    Corresponding Source in the same way through the same place at "
    "no\\line\n"
    "    further charge.  You need not require recipients to copy the\\line\n"
    "    Corresponding Source along with the object code.  If the place "
    "to\\line\n"
    "    copy the object code is a network server, the Corresponding "
    "Source\\line\n"
    "    may be on a different server (operated by you or a third "
    "party)\\line\n"
    "    that supports equivalent copying facilities, provided you "
    "maintain\\line\n"
    "    clear directions next to the object code saying where to find "
    "the\\line\n"
    "    Corresponding Source.  Regardless of what server hosts the\\line\n"
    "    Corresponding Source, you remain obligated to ensure that it "
    "is\\line\n"
    "    available for as long as needed to satisfy these requirements.\\line\n"
    "\\line\n"
    "    e) Convey the object code using peer-to-peer transmission, "
    "provided\\line\n"
    "    you inform other peers where the object code and Corresponding\\line\n"
    "    Source of the work are being offered to the general public at "
    "no\\line\n"
    "    charge under subsection 6d.\\line\n"
    "\\line\n"
    "  A separable portion of the object code, whose source code is "
    "excluded\\line\n"
    "from the Corresponding Source as a System Library, need not be\\line\n"
    "included in conveying the object code work.\\line\n"
    "\\line\n"
    "  A \"User Product\" is either (1) a \"consumer product\", which means "
    "any\\line\n"
    "tangible personal property which is normally used for personal, "
    "family,\\line\n"
    "or household purposes, or (2) anything designed or sold for "
    "incorporation\\line\n"
    "into a dwelling.  In determining whether a product is a consumer "
    "product,\\line\n"
    "doubtful cases shall be resolved in favor of coverage.  For a "
    "particular\\line\n"
    "product received by a particular user, \"normally used\" refers to "
    "a\\line\n"
    "typical or common use of that class of product, regardless of the "
    "status\\line\n"
    "of the particular user or of the way in which the particular user\\line\n"
    "actually uses, or expects or is expected to use, the product.  A "
    "product\\line\n"
    "is a consumer product regardless of whether the product has "
    "substantial\\line\n"
    "commercial, industrial or non-consumer uses, unless such uses "
    "represent\\line\n"
    "the only significant mode of use of the product.\\line\n"
    "\\line\n"
    "  \"Installation Information\" for a User Product means any "
    "methods,\\line\n"
    "procedures, authorization keys, or other information required to "
    "install\\line\n"
    "and execute modified versions of a covered work in that User Product "
    "from\\line\n"
    "a modified version of its Corresponding Source.  The information "
    "must\\line\n"
    "suffice to ensure that the continued functioning of the modified "
    "object\\line\n"
    "code is in no case prevented or interfered with solely because\\line\n"
    "modification has been made.\\line\n"
    "\\line\n"
    "  If you convey an object code work under this section in, or with, "
    "or\\line\n"
    "specifically for use in, a User Product, and the conveying occurs "
    "as\\line\n"
    "part of a transaction in which the right of possession and use of "
    "the\\line\n"
    "User Product is transferred to the recipient in perpetuity or for "
    "a\\line\n"
    "fixed term (regardless of how the transaction is characterized), "
    "the\\line\n"
    "Corresponding Source conveyed under this section must be "
    "accompanied\\line\n"
    "by the Installation Information.  But this requirement does not "
    "apply\\line\n"
    "if neither you nor any third party retains the ability to install\\line\n"
    "modified object code on the User Product (for example, the work "
    "has\\line\n"
    "been installed in ROM).\\line\n"
    "\\line\n"
    "  The requirement to provide Installation Information does not include "
    "a\\line\n"
    "requirement to continue to provide support service, warranty, or "
    "updates\\line\n"
    "for a work that has been modified or installed by the recipient, or "
    "for\\line\n"
    "the User Product in which it has been modified or installed.  Access to "
    "a\\line\n"
    "network may be denied when the modification itself materially and\\line\n"
    "adversely affects the operation of the network or violates the rules "
    "and\\line\n"
    "protocols for communication across the network.\\line\n"
    "\\line\n"
    "  Corresponding Source conveyed, and Installation Information "
    "provided,\\line\n"
    "in accord with this section must be in a format that is publicly\\line\n"
    "documented (and with an implementation available to the public in\\line\n"
    "source code form), and must require no special password or key for\\line\n"
    "unpacking, reading or copying.\\line\n"
    "\\line\n"
    "  7. Additional Terms.\\line\n"
    "\\line\n"
    "  \"Additional permissions\" are terms that supplement the terms of "
    "this\\line\n"
    "License by making exceptions from one or more of its conditions.\\line\n"
    "Additional permissions that are applicable to the entire Program "
    "shall\\line\n"
    "be treated as though they were included in this License, to the "
    "extent\\line\n"
    "that they are valid under applicable law.  If additional "
    "permissions\\line\n"
    "apply only to part of the Program, that part may be used "
    "separately\\line\n"
    "under those permissions, but the entire Program remains governed "
    "by\\line\n"
    "this License without regard to the additional permissions.\\line\n"
    "\\line\n"
    "  When you convey a copy of a covered work, you may at your option\\line\n"
    "remove any additional permissions from that copy, or from any part "
    "of\\line\n"
    "it.  (Additional permissions may be written to require their own\\line\n"
    "removal in certain cases when you modify the work.)  You may place\\line\n"
    "additional permissions on material, added by you to a covered "
    "work,\\line\n"
    "for which you have or can give appropriate copyright permission.\\line\n"
    "\\line\n"
    "  Notwithstanding any other provision of this License, for material "
    "you\\line\n"
    "add to a covered work, you may (if authorized by the copyright holders "
    "of\\line\n"
    "that material) supplement the terms of this License with terms:\\line\n"
    "\\line\n"
    "    a) Disclaiming warranty or limiting liability differently from "
    "the\\line\n"
    "    terms of sections 15 and 16 of this License; or\\line\n"
    "\\line\n"
    "    b) Requiring preservation of specified reasonable legal notices "
    "or\\line\n"
    "    author attributions in that material or in the Appropriate "
    "Legal\\line\n"
    "    Notices displayed by works containing it; or\\line\n"
    "\\line\n"
    "    c) Prohibiting misrepresentation of the origin of that material, "
    "or\\line\n"
    "    requiring that modified versions of such material be marked in\\line\n"
    "    reasonable ways as different from the original version; or\\line\n"
    "\\line\n"
    "    d) Limiting the use for publicity purposes of names of licensors "
    "or\\line\n"
    "    authors of the material; or\\line\n"
    "\\line\n"
    "    e) Declining to grant rights under trademark law for use of "
    "some\\line\n"
    "    trade names, trademarks, or service marks; or\\line\n"
    "\\line\n"
    "    f) Requiring indemnification of licensors and authors of that\\line\n"
    "    material by anyone who conveys the material (or modified versions "
    "of\\line\n"
    "    it) with contractual assumptions of liability to the recipient, "
    "for\\line\n"
    "    any liability that these contractual assumptions directly impose "
    "on\\line\n"
    "    those licensors and authors.\\line\n"
    "\\line\n"
    "  All other non-permissive additional terms are considered "
    "\"further\\line\n"
    "restrictions\" within the meaning of section 10.  If the Program as "
    "you\\line\n"
    "received it, or any part of it, contains a notice stating that it "
    "is\\line\n"
    "governed by this License along with a term that is a further\\line\n"
    "restriction, you may remove that term.  If a license document "
    "contains\\line\n"
    "a further restriction but permits relicensing or conveying under "
    "this\\line\n"
    "License, you may add to a covered work material governed by the "
    "terms\\line\n"
    "of that license document, provided that the further restriction "
    "does\\line\n"
    "not survive such relicensing or conveying.\\line\n"
    "\\line\n"
    "  If you add terms to a covered work in accord with this section, "
    "you\\line\n"
    "must place, in the relevant source files, a statement of the\\line\n"
    "additional terms that apply to those files, or a notice indicating\\line\n"
    "where to find the applicable terms.\\line\n"
    "\\line\n"
    "  Additional terms, permissive or non-permissive, may be stated in "
    "the\\line\n"
    "form of a separately written license, or stated as exceptions;\\line\n"
    "the above requirements apply either way.\\line\n"
    "\\line\n"
    "  8. Termination.\\line\n"
    "\\line\n"
    "  You may not propagate or modify a covered work except as "
    "expressly\\line\n"
    "provided under this License.  Any attempt otherwise to propagate "
    "or\\line\n"
    "modify it is void, and will automatically terminate your rights "
    "under\\line\n"
    "this License (including any patent licenses granted under the "
    "third\\line\n"
    "paragraph of section 11).\\line\n"
    "\\line\n"
    "  However, if you cease all violation of this License, then your\\line\n"
    "license from a particular copyright holder is reinstated (a)\\line\n"
    "provisionally, unless and until the copyright holder explicitly "
    "and\\line\n"
    "finally terminates your license, and (b) permanently, if the "
    "copyright\\line\n"
    "holder fails to notify you of the violation by some reasonable "
    "means\\line\n"
    "prior to 60 days after the cessation.\\line\n"
    "\\line\n"
    "  Moreover, your license from a particular copyright holder is\\line\n"
    "reinstated permanently if the copyright holder notifies you of the\\line\n"
    "violation by some reasonable means, this is the first time you "
    "have\\line\n"
    "received notice of violation of this License (for any work) from "
    "that\\line\n"
    "copyright holder, and you cure the violation prior to 30 days "
    "after\\line\n"
    "your receipt of the notice.\\line\n"
    "\\line\n"
    "  Termination of your rights under this section does not terminate "
    "the\\line\n"
    "licenses of parties who have received copies or rights from you "
    "under\\line\n"
    "this License.  If your rights have been terminated and not "
    "permanently\\line\n"
    "reinstated, you do not qualify to receive new licenses for the "
    "same\\line\n"
    "material under section 10.\\line\n"
    "\\line\n"
    "  9. Acceptance Not Required for Having Copies.\\line\n"
    "\\line\n"
    "  You are not required to accept this License in order to receive "
    "or\\line\n"
    "run a copy of the Program.  Ancillary propagation of a covered "
    "work\\line\n"
    "occurring solely as a consequence of using peer-to-peer "
    "transmission\\line\n"
    "to receive a copy likewise does not require acceptance.  However,\\line\n"
    "nothing other than this License grants you permission to propagate "
    "or\\line\n"
    "modify any covered work.  These actions infringe copyright if you "
    "do\\line\n"
    "not accept this License.  Therefore, by modifying or propagating a\\line\n"
    "covered work, you indicate your acceptance of this License to do "
    "so.\\line\n"
    "\\line\n"
    "  10. Automatic Licensing of Downstream Recipients.\\line\n"
    "\\line\n"
    "  Each time you convey a covered work, the recipient automatically\\line\n"
    "receives a license from the original licensors, to run, modify and\\line\n"
    "propagate that work, subject to this License.  You are not "
    "responsible\\line\n"
    "for enforcing compliance by third parties with this License.\\line\n"
    "\\line\n"
    "  An \"entity transaction\" is a transaction transferring control of "
    "an\\line\n"
    "organization, or substantially all assets of one, or subdividing "
    "an\\line\n"
    "organization, or merging organizations.  If propagation of a "
    "covered\\line\n"
    "work results from an entity transaction, each party to that\\line\n"
    "transaction who receives a copy of the work also receives whatever\\line\n"
    "licenses to the work the party's predecessor in interest had or "
    "could\\line\n"
    "give under the previous paragraph, plus a right to possession of "
    "the\\line\n"
    "Corresponding Source of the work from the predecessor in interest, "
    "if\\line\n"
    "the predecessor has it or can get it with reasonable efforts.\\line\n"
    "\\line\n"
    "  You may not impose any further restrictions on the exercise of "
    "the\\line\n"
    "rights granted or affirmed under this License.  For example, you "
    "may\\line\n"
    "not impose a license fee, royalty, or other charge for exercise of\\line\n"
    "rights granted under this License, and you may not initiate "
    "litigation\\line\n"
    "(including a cross-claim or counterclaim in a lawsuit) alleging "
    "that\\line\n"
    "any patent claim is infringed by making, using, selling, offering "
    "for\\line\n"
    "sale, or importing the Program or any portion of it.\\line\n"
    "\\line\n"
    "  11. Patents.\\line\n"
    "\\line\n"
    "  A \"contributor\" is a copyright holder who authorizes use under "
    "this\\line\n"
    "License of the Program or a work on which the Program is based.  "
    "The\\line\n"
    "work thus licensed is called the contributor's \"contributor "
    "version\".\\line\n"
    "\\line\n"
    "  A contributor's \"essential patent claims\" are all patent "
    "claims\\line\n"
    "owned or controlled by the contributor, whether already acquired "
    "or\\line\n"
    "hereafter acquired, that would be infringed by some manner, "
    "permitted\\line\n"
    "by this License, of making, using, or selling its contributor "
    "version,\\line\n"
    "but do not include claims that would be infringed only as a\\line\n"
    "consequence of further modification of the contributor version.  "
    "For\\line\n"
    "purposes of this definition, \"control\" includes the right to "
    "grant\\line\n"
    "patent sublicenses in a manner consistent with the requirements of\\line\n"
    "this License.\\line\n"
    "\\line\n"
    "  Each contributor grants you a non-exclusive, worldwide, "
    "royalty-free\\line\n"
    "patent license under the contributor's essential patent claims, to\\line\n"
    "make, use, sell, offer for sale, import and otherwise run, modify "
    "and\\line\n"
    "propagate the contents of its contributor version.\\line\n"
    "\\line\n"
    "  In the following three paragraphs, a \"patent license\" is any "
    "express\\line\n"
    "agreement or commitment, however denominated, not to enforce a "
    "patent\\line\n"
    "(such as an express permission to practice a patent or covenant not "
    "to\\line\n"
    "sue for patent infringement).  To \"grant\" such a patent license to "
    "a\\line\n"
    "party means to make such an agreement or commitment not to enforce "
    "a\\line\n"
    "patent against the party.\\line\n"
    "\\line\n"
    "  If you convey a covered work, knowingly relying on a patent "
    "license,\\line\n"
    "and the Corresponding Source of the work is not available for "
    "anyone\\line\n"
    "to copy, free of charge and under the terms of this License, through "
    "a\\line\n"
    "publicly available network server or other readily accessible "
    "means,\\line\n"
    "then you must either (1) cause the Corresponding Source to be so\\line\n"
    "available, or (2) arrange to deprive yourself of the benefit of "
    "the\\line\n"
    "patent license for this particular work, or (3) arrange, in a "
    "manner\\line\n"
    "consistent with the requirements of this License, to extend the "
    "patent\\line\n"
    "license to downstream recipients.  \"Knowingly relying\" means you "
    "have\\line\n"
    "actual knowledge that, but for the patent license, your conveying "
    "the\\line\n"
    "covered work in a country, or your recipient's use of the covered "
    "work\\line\n"
    "in a country, would infringe one or more identifiable patents in "
    "that\\line\n"
    "country that you have reason to believe are valid.\\line\n"
    "\\line\n"
    "  If, pursuant to or in connection with a single transaction or\\line\n"
    "arrangement, you convey, or propagate by procuring conveyance of, "
    "a\\line\n"
    "covered work, and grant a patent license to some of the parties\\line\n"
    "receiving the covered work authorizing them to use, propagate, "
    "modify\\line\n"
    "or convey a specific copy of the covered work, then the patent "
    "license\\line\n"
    "you grant is automatically extended to all recipients of the "
    "covered\\line\n"
    "work and works based on it.\\line\n"
    "\\line\n"
    "  A patent license is \"discriminatory\" if it does not include "
    "within\\line\n"
    "the scope of its coverage, prohibits the exercise of, or is\\line\n"
    "conditioned on the non-exercise of one or more of the rights that "
    "are\\line\n"
    "specifically granted under this License.  You may not convey a "
    "covered\\line\n"
    "work if you are a party to an arrangement with a third party that "
    "is\\line\n"
    "in the business of distributing software, under which you make "
    "payment\\line\n"
    "to the third party based on the extent of your activity of "
    "conveying\\line\n"
    "the work, and under which the third party grants, to any of the\\line\n"
    "parties who would receive the covered work from you, a "
    "discriminatory\\line\n"
    "patent license (a) in connection with copies of the covered work\\line\n"
    "conveyed by you (or copies made from those copies), or (b) "
    "primarily\\line\n"
    "for and in connection with specific products or compilations that\\line\n"
    "contain the covered work, unless you entered into that "
    "arrangement,\\line\n"
    "or that patent license was granted, prior to 28 March 2007.\\line\n"
    "\\line\n"
    "  Nothing in this License shall be construed as excluding or "
    "limiting\\line\n"
    "any implied license or other defenses to infringement that may\\line\n"
    "otherwise be available to you under applicable patent law.\\line\n"
    "\\line\n"
    "  12. No Surrender of Others' Freedom.\\line\n"
    "\\line\n"
    "  If conditions are imposed on you (whether by court order, agreement "
    "or\\line\n"
    "otherwise) that contradict the conditions of this License, they do "
    "not\\line\n"
    "excuse you from the conditions of this License.  If you cannot convey "
    "a\\line\n"
    "covered work so as to satisfy simultaneously your obligations under "
    "this\\line\n"
    "License and any other pertinent obligations, then as a consequence you "
    "may\\line\n"
    "not convey it at all.  For example, if you agree to terms that obligate "
    "you\\line\n"
    "to collect a royalty for further conveying from those to whom you "
    "convey\\line\n"
    "the Program, the only way you could satisfy both those terms and "
    "this\\line\n"
    "License would be to refrain entirely from conveying the Program.\\line\n"
    "\\line\n"
    "  13. Use with the GNU Affero General Public License.\\line\n"
    "\\line\n"
    "  Notwithstanding any other provision of this License, you have\\line\n"
    "permission to link or combine any covered work with a work "
    "licensed\\line\n"
    "under version 3 of the GNU Affero General Public License into a "
    "single\\line\n"
    "combined work, and to convey the resulting work.  The terms of "
    "this\\line\n"
    "License will continue to apply to the part which is the covered "
    "work,\\line\n"
    "but the special requirements of the GNU Affero General Public "
    "License,\\line\n"
    "section 13, concerning interaction through a network will apply to "
    "the\\line\n"
    "combination as such.\\line\n"
    "\\line\n"
    "  14. Revised Versions of this License.\\line\n"
    "\\line\n"
    "  The Free Software Foundation may publish revised and/or new versions "
    "of\\line\n"
    "the GNU General Public License from time to time.  Such new versions "
    "will\\line\n"
    "be similar in spirit to the present version, but may differ in detail "
    "to\\line\n"
    "address new problems or concerns.\\line\n"
    "\\line\n"
    "  Each version is given a distinguishing version number.  If the\\line\n"
    "Program specifies that a certain numbered version of the GNU "
    "General\\line\n"
    "Public License \"or any later version\" applies to it, you have "
    "the\\line\n"
    "option of following the terms and conditions either of that "
    "numbered\\line\n"
    "version or of any later version published by the Free Software\\line\n"
    "Foundation.  If the Program does not specify a version number of "
    "the\\line\n"
    "GNU General Public License, you may choose any version ever "
    "published\\line\n"
    "by the Free Software Foundation.\\line\n"
    "\\line\n"
    "  If the Program specifies that a proxy can decide which future\\line\n"
    "versions of the GNU General Public License can be used, that "
    "proxy's\\line\n"
    "public statement of acceptance of a version permanently authorizes "
    "you\\line\n"
    "to choose that version for the Program.\\line\n"
    "\\line\n"
    "  Later license versions may give you additional or different\\line\n"
    "permissions.  However, no additional obligations are imposed on "
    "any\\line\n"
    "author or copyright holder as a result of your choosing to follow "
    "a\\line\n"
    "later version.\\line\n"
    "\\line\n"
    "  15. Disclaimer of Warranty.\\line\n"
    "\\line\n"
    "  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY\\line\n"
    "APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE "
    "COPYRIGHT\\line\n"
    "HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT "
    "WARRANTY\\line\n"
    "OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED "
    "TO,\\line\n"
    "THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A "
    "PARTICULAR\\line\n"
    "PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE "
    "PROGRAM\\line\n"
    "IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST "
    "OF\\line\n"
    "ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\\line\n"
    "\\line\n"
    "  16. Limitation of Liability.\\line\n"
    "\\line\n"
    "  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN "
    "WRITING\\line\n"
    "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR "
    "CONVEYS\\line\n"
    "THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING "
    "ANY\\line\n"
    "GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF "
    "THE\\line\n"
    "USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS "
    "OF\\line\n"
    "DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR "
    "THIRD\\line\n"
    "PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER "
    "PROGRAMS),\\line\n"
    "EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY "
    "OF\\line\n"
    "SUCH DAMAGES.\\line\n"
    "\\line\n"
    "  17. Interpretation of Sections 15 and 16.\\line\n"
    "\\line\n"
    "  If the disclaimer of warranty and limitation of liability "
    "provided\\line\n"
    "above cannot be given local legal effect according to their terms,\\line\n"
    "reviewing courts shall apply local law that most closely "
    "approximates\\line\n"
    "an absolute waiver of all civil liability in connection with the\\line\n"
    "Program, unless a warranty or assumption of liability accompanies "
    "a\\line\n"
    "copy of the Program in return for a fee.\\line\n"
    "\\line\n"
    "                     END OF TERMS AND CONDITIONS\\line\n"
    "}";

#endif
